/*
Apicurio Registry API [v2]

Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 

API version: 2.4.x
Contact: apicurio@lists.jboss.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package registryclient

import (
	"encoding/json"
	"fmt"
)

// HandleReferencesType How to handle references when retrieving content.  References can either be left unchanged (`PRESERVE`), re-written so they are valid in the context of the registry (`REWRITE`), or fully dereferenced such that all externally referenced content is internalized (`DEREFERENCE`).
type HandleReferencesType string

// List of HandleReferencesType
const (
	PRESERVE HandleReferencesType = "PRESERVE"
	DEREFERENCE HandleReferencesType = "DEREFERENCE"
	REWRITE HandleReferencesType = "REWRITE"
)

// All allowed values of HandleReferencesType enum
var AllowedHandleReferencesTypeEnumValues = []HandleReferencesType{
	"PRESERVE",
	"DEREFERENCE",
	"REWRITE",
}

func (v *HandleReferencesType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := HandleReferencesType(value)
	for _, existing := range AllowedHandleReferencesTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid HandleReferencesType", value)
}

// NewHandleReferencesTypeFromValue returns a pointer to a valid HandleReferencesType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHandleReferencesTypeFromValue(v string) (*HandleReferencesType, error) {
	ev := HandleReferencesType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for HandleReferencesType: valid values are %v", v, AllowedHandleReferencesTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v HandleReferencesType) IsValid() bool {
	for _, existing := range AllowedHandleReferencesTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to HandleReferencesType value
func (v HandleReferencesType) Ptr() *HandleReferencesType {
	return &v
}

type NullableHandleReferencesType struct {
	value *HandleReferencesType
	isSet bool
}

func (v NullableHandleReferencesType) Get() *HandleReferencesType {
	return v.value
}

func (v *NullableHandleReferencesType) Set(val *HandleReferencesType) {
	v.value = val
	v.isSet = true
}

func (v NullableHandleReferencesType) IsSet() bool {
	return v.isSet
}

func (v *NullableHandleReferencesType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandleReferencesType(val *HandleReferencesType) *NullableHandleReferencesType {
	return &NullableHandleReferencesType{value: val, isSet: true}
}

func (v NullableHandleReferencesType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandleReferencesType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

