/*
Apicurio Registry API [v2]

Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 

API version: 2.4.x
Contact: apicurio@lists.jboss.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package registryclient

import (
	"encoding/json"
)

// checks if the NewComment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewComment{}

// NewComment 
type NewComment struct {
	Value string `json:"value"`
}

// NewNewComment instantiates a new NewComment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewComment(value string) *NewComment {
	this := NewComment{}
	this.Value = value
	return &this
}

// NewNewCommentWithDefaults instantiates a new NewComment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewCommentWithDefaults() *NewComment {
	this := NewComment{}
	return &this
}

// GetValue returns the Value field value
func (o *NewComment) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NewComment) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NewComment) SetValue(v string) {
	o.Value = v
}

func (o NewComment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewComment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableNewComment struct {
	value *NewComment
	isSet bool
}

func (v NullableNewComment) Get() *NewComment {
	return v.value
}

func (v *NullableNewComment) Set(val *NewComment) {
	v.value = val
	v.isSet = true
}

func (v NullableNewComment) IsSet() bool {
	return v.isSet
}

func (v *NullableNewComment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewComment(val *NewComment) *NullableNewComment {
	return &NullableNewComment{value: val, isSet: true}
}

func (v NullableNewComment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewComment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


